version: "3.8"
services: 
    sqlServer:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - SA_PASSWORD=admin*123
            - ACCEPT_EULA=Y
        ports:
            - 1433:1433
        volumes: 
            - ./bkp:/home/bkp